add get_filter_logs
hswick/exw3 pull request #40
Opened 2020-09-12 23:25 UTC by maxwolff

2020-09-13 17:05 UTC, hswick commented on lib/exw3.ex
> +            formatted_log =
Can you put this anonymous function into a helper function, please.

2020-09-13 17:07 UTC, hswick requested changes
This looks fine. Only a few things.

Commented about turning that anonymous function into a descriptive helper function, something like `format_log`

Would be great if a a test can be added.

And if you can bump the the elixir version in .travis.yml to match mix.exs so the CI can run properly.

Thanks!

2020-11-28 17:20 UTC, rupurt requested changes

2020-11-28 17:20 UTC, rupurt commented on lib/exw3.ex
> +  def get_filter_logs(filter_id) do
@maxwolff should this be called `get_logs` and use the RPC function call `eth_getLogs`? I don't see an RPC function called `eth_getFilterLogs`.

2023-10-27 03:31 UTC, closed without merging